### ISSUE TITLE
RuntimeError: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)

### ISSUE THREAD

**Issue by AugmentedRealityCat** [MMqd/kandinsky-for-automatic1111#1]
I have tried to reduce my installation to its most simple, I removed most of the extensions (even LoRA), I stopped using OPT optimization, I tried with and without xformers, and with DoggetX optimization as well as without any optimizer at all. I tried with `--no-half` and `--no-half-vae`. I tried adding `set CUBLAS_WORKSPACE_CONFIG=:4096:8` to my webui-user.bat, but no matter what I did I still haven't got it to work. All required models seem to have been downloaded - I saw them in a previous try, and now it seems to jump over that part seeing it's all there already.

install info : 
version: [v1.3.2-241-g59419bd6](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/59419bd64a1581caccaac04dceb66c1c069a2db1)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [6ce0161689](https://google.com/search?q=6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa)

```
venv "C:\stable-diffusion-webui\venvxformers\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2-241-g59419bd6
Commit hash: 59419bd64a1581caccaac04dceb66c1c069a2db1
Installing requirements
Collecting git+https://github.com/huggingface/diffusers
  Cloning https://github.com/huggingface/diffusers to c:\users\user\appdata\local\temp\pip-req-build-p06s6odc
  Resolved https://github.com/huggingface/diffusers to commit abbfe4b5b7a9508169e69476a951a1a6dd86c927
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Pillow in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (9.5.0)
Requirement already satisfied: requests in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (2.31.0)
Requirement already satisfied: regex!=2019.12.17 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (2023.6.3)
Requirement already satisfied: filelock in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (3.12.0)
Requirement already satisfied: importlib-metadata in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (6.6.0)
Requirement already satisfied: huggingface-hub>=0.13.2 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (0.15.1)
Requirement already satisfied: numpy in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from diffusers==0.18.0.dev0) (1.23.5)
Requirement already satisfied: tqdm>=4.42.1 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from huggingface-hub>=0.13.2->diffusers==0.18.0.dev0) (4.65.0)
Requirement already satisfied: packaging>=20.9 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from huggingface-hub>=0.13.2->diffusers==0.18.0.dev0) (23.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from huggingface-hub>=0.13.2->diffusers==0.18.0.dev0) (4.6.3)
Requirement already satisfied: pyyaml>=5.1 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from huggingface-hub>=0.13.2->diffusers==0.18.0.dev0) (6.0)
Requirement already satisfied: fsspec in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from huggingface-hub>=0.13.2->diffusers==0.18.0.dev0) (2023.5.0)
Requirement already satisfied: zipp>=0.5 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from importlib-metadata->diffusers==0.18.0.dev0) (3.15.0)
Requirement already satisfied: idna<4,>=2.5 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from requests->diffusers==0.18.0.dev0) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from requests->diffusers==0.18.0.dev0) (2023.5.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from requests->diffusers==0.18.0.dev0) (3.1.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from requests->diffusers==0.18.0.dev0) (1.26.16)
Requirement already satisfied: colorama in c:\stable-diffusion-webui\venvxformers\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.2->diffusers==0.18.0.dev0) (0.4.6)

Launching Web UI with arguments: --no-half --no-half-vae
No module 'xformers'. Proceeding without it.
Loading weights [6ce0161689] from C:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
preload_extensions_git_metadata for 8 extensions took 0.10s
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.8s (import torch: 1.8s, import gradio: 0.6s, import ldm: 0.3s, other imports: 0.4s, load scripts: 3.3s, create ui: 0.2s, gradio launch: 0.1s).
DiffusionWrapper has 859.52 M params.
Disabling attention optimization
Textual inversion embeddings loaded(298): 0lg4kury, 16-token-negative-deliberate-neg, 512paintstyle1, 512paintstyle3, 512paintstyle3-light, 512speedpainter, 80sdarkfantasysd15b, AdriannePalicki1, aid28, aidv1-neg, anatomical-illustration, ancient-ruin, ancient-ruin-forest, angry512, anime-AI-being, archmagazine, art by sel-foc, AshleyCipher, Asian-Less, Asian-Less-Toon, atompunkstylesd15, avGdnr, b_w, backrooms, bad-artist, bad-artist-anime, bad-hands-5, bad-image-9600, bad-image-v2-11000, bad-image-v2-27000, bad-image-v2-39000, bad_prompt, bad_prompt (2), bad_prompt_version2, badhandsv5-neg, badv3, badv4, badv5, Boichi2_style-6000, By bad artist -neg, cervicalMRI, CFStyle, CharTurner, CharTurnerV2, chemicalbending_stableDiffusion, chibi_style, close portrait, cobwebber, coloring-book-style, coop himmelblau museum, cry5t415ku11, dangercrow, dangerdonkey, dangerhawk, dangermouse, dark-forest, Dark_fantasy, dark_ouroboros, DarkFantasy, defiance512, donglu, dragon, dragon inn-18500, drr-style, EasyNegative, easynegative, edwardhopperembed, el-salvador-style-style, ErinMoriarty2, Exodus-Styling, expomech_expomech, fantasycharacter, fenn_jesus, Floral_Graffiti, flower_style, françoise hardy, fruityslices3, gothbuilding, grin512, gushu, gushuman, gustavedore, HannahWaddingham2, happy512, hgr1ce-step-240, hndpnt-145, hndpnt-261, hobbithouse, hongxinliang, hrgiger-drmacabre_or_barba, HudsonHornet, HyperStylizeV6, iconPxvGameHangv001_iconPxvGameHangv001, ilo-kunst, ink_style, josangonzalez, KateMara2, kc16-4000-sd1-5, kidbooks, kkw-ami, kkw-Autumn, kkw-bp, kkw-card, kkw-chibi, kkw-el-fire, kkw-el-grass, kkw-el-ice, kkw-el-Lightning , kkw-el-rock, kkw-el-sand, kkw-el-water, kkw-fat-m, kkw-hdr, kkw-horror, kkw-hyb-eleph, kkw-hyb-spider, kkw-macro, kkw-medieval, kkw-micro, kkw-old, kkw-paper, kkw-ph1, kkw-ph1-neg, kkw-splatter, kkw-Spring, kkw-Summer, kkw-Winter, kkw-xeno, land_style, lands_between, landscape_style, laugh512, lightning_style, lightning_style-7500, LiliReinhart1, liminal-spaces-2-0, line-art, line-style, liquidlight, lol_splash, lr, marblingart, marsattacks3, max-headroom , memphisstyle-6750, metropolis_e, midthunder, minimal_gradient, mmax00, moe-bius, moebius, neg_facelift512, neon-ground-astronaut, neonbath, nervous512, NG_DeepNegative_V1_16T, NG_DeepNegative_V1_2T, NG_DeepNegative_V1_32T, NG_DeepNegative_V1_4T, NG_DeepNegative_V1_64T, NG_DeepNegative_V1_75T, np_simple_negatives, np_simple_negatives_v2-neg, oldstyle_v1, olfn, one-line-drawing, pantone-milk, pastel_style, pen-ink-portraits-bennorthen, photozoov15, PigglyWiggly, PlanIt, pmantis, poly-hd, qualityzoov15, quimbystyle, rainbow-candy, rcnz_style, realisticvision-negative-embedding, renderzoov15, repeat, RFKTR_bontrex, RFKTR_bontrex-150, rfktr_circrex, RFKTR_rootrex, RFKTR_sinetempore, rico_tubbs, rmadanegative4_sd15-neg, rw1510, rz-neg-15-foranalog, sad512, schnucks, sd15_journalSketch, shev-linocut, shock512, silky-folds, skelewags, slpashter, slpashter_2, smile512, Smrai_style, southofthebordersd15, star_style, stardeaf-greenmageddon, stardeaf-inkmage-orange , stardeaf-inkmage-white , steampunkgranny, structurezoov15, Style-Autumn, Style-Autumn-neg, Style-BladeRunner2049-8v, style-bridal, Style-Empire, Style-Empire-neg, Style-Glass, Style-Glorious, Style-Glorious-neg, Style-Hamunaptra, Style-Info, Style-Italy, Style-Japan, Style-Kilt, Style-Kitchen, Style-Kitchen-neg, style-kotor, Style-Moana, Style-Moana-neg, style-nagel, Style-NebMagic, Style-NebMagic-neg, Style-Necromancy, style-paintmagic, Style-Petal, Style-Petal-neg, style-pnmagic, Style-Princess, Style-Psycho, Style-Psycho-neg, Style-Renaissance, Style-Renaissance-neg, style-rustmagic, style-rustmagic-neg, style-sylvamagic, Style-TronLegacy-12v-v2, Style-TronLegacy-8v-B, style-widow, Style-Winter, Style-Winter-neg, Style-Witcher3, style_cctv, style_the grand budapest hotel, style_tombraider, suijing, super_ugly1t, super_ugly3t, taiji, tarot512, TaylorSwift2, test, tfftgirlv05, tffthairv07nike, tffthairv07phto, tloustyle, toy_ugly, tropical-island, trypophobia, u1t1m4t3w4rr10r, ukiyoestyle-1500, Unspeakable-Horrors-16v, Unspeakable-Horrors-24v, Unspeakable-Horrors-32v, Unspeakable-Horrors-48v, Unspeakable-Horrors-64v, Unspeakable-Horrors-Composition, utpvirt, vintagemap_f, vladstudio, was-battletech, was-diablo, was-dieselpunk, was-gunpla, was-hs, was-hs-v2, was-jaeger, was-mecha, was-senua, was-steampunk, was-vb, wasmoebius, wassnonam-39400, wb17_din_djarin, winter_style, winter_style-4500, winter_style-7500, wire-angels, zhongshinei, zhubao, ZoeSaldana2
Textual inversion embeddings skipped(185): 21charturnerv2, ActionHelper, AnalogFilm768-BW-Classic, AnalogFilm768-BW-Modern, AnalogFilm768-BW-Tintype, AnalogFilm768-BW-Vintage, AnalogFilm768-Old-School, AnalogFilm768, anthro, Apoc768, Apocofy, aslanscifi-v1, aslanscifi-v2, bruegel-style-artwork, CandyPunk, CandyPunk_V2, CarHelper, cgart, Chadeisson, ChemPunk-96, Cinema768-Analog, Cinema768-BW, Cinema768-Classic, Cinema768-Digital, Cinema768-SilentFilm, CinemaHelper, conceptart-200, conceptart-200_V2, conceptart-300, conceptart-300_V2, conceptart-400, conceptart-400_V2, conceptart-500, conceptart-500_V2, CutAway-420, CutAway-420_V2, CutAway-460, CutAway-460_V2, CutAway-500, CutAway-500_V2, dangergoose, dangerhorse, dangermoose, dangerowl, DaveSpaceFour, DaveSpaceOne, Decay768, Ellsworth_Kelly, EMB_Black_Marble_Style_V5-2000, emb_blck_egpt_v4-1000, FFbF_aTon, FFbF_effect, FFbF_Heavy, FFbF_light, FFbF_neon, FFbF_power, FloralMarble-150, FloralMarble-250, FloralMarble-400, FloralMarble, fragmenv2, fragmenv2_V2, glitch, HeartArt-1000, HeartArt-1500, HeartArt-2000, HeartArt, hellscape768, HorrorByDave, HydroFood, HyperFluid, HyperNuke, HyperSmoke, InkPunk768, InkPunkHeavy768, InkPunkLandscapes768, InkPunkLite768, inksketchcolour1, inksketchcolour1subtle, Inksplat768, knollingcase-embeddings-sd-v2-0_V2, knollingcase_32, laconia, latteart, lavastyle-12000, Lavastyle, laxpeint, laxpeintV2, mdjrny-ppc, midjourney_sd_2_0, midjourney_style_for_v2_use_in the style of midjourney, midjourney_style_for_v2_use_in the style of midjourney_V2, mj-gs, mjart, mjSymbiote, NegLowRes-1200, NegLowRes-200, NegLowRes-2400, NegLowRes-500, NegMutation-1200, negmutation-200, NegMutation-2400, negmutation-500, neg_Colorizer768-Cool, Neg_Colorizer768-Intense, neg_Colorizer768-neutral, Neg_Colorizer768-Vibrant, Neg_Colorizer768-Vivid, neg_Colorizer768-Warm, Neg_Facelift768, nfixer, no_unrealistic768, nrealfixer, Painted Abstract, painted_abstract, painted_landscape, painted_landscape_V2, PaintStyle1, PaintStyle3, PaintStyle4, paintstyle5, paintstyle6-neg, paintstyle6, paintstyle8, papercutcraft-v2, ParchArt, PhotoHelper, PhotoHelper_V2, photozoov21, pixelart, PlanIt2, PMondrian, PortraitHelper, PortraitHelper_V2, protogemb, protogemb2, qualityzoov21, Rain_and_Monsters_prue640v2, Rain_and_Monsters_prue640v2_V2, remix, remix_V2, renderzoov21, retrofutur, rmadaneg-neg, Ruin768, rz-neg-foranalogportrait, rz-neg-forbettercontrast, rz-neg-general, ScaryMonsters, ScaryMonstersV2, SCG768-Bliss, SCG768-Euphoria, SCG768-Illustrate, SCG768-Nebula, SocialistRealism, SpanishElegy, structurezoov21, style-bridal_sd2, style-princess_sd2, style-widow_sd2, tarot768, tf86movie-550, tfboxart-100, tfboxart-250, tfboxart-600, tfboxart, trinkdber, UlukInkSketch2, UNBADS, UNREALS, UrbanJungle, Vint-3000, Vint, VintageHelper-600, VintageHelper, waterworksv2-500, waterworksv2-5000, wrong_embedding_sd_2_0, wrong_embedding_sd_2_0_V2, ZiCyb, ZiCybB, ZiCybL, ZiCybP, zombified768, Zootopiav4
Model loaded in 3.0s (load weights from disk: 0.3s, create model: 0.2s, apply weights to model: 0.5s, move model to device: 1.6s, load textual inversion embeddings: 0.2s).
Disabling attention optimization
100%|██████████████████████████████████████████████████████████████████████████████████| 64/64 [00:06<00:00,  9.48it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 11.26it/s]
Unloaded weights 0.0s.█████████████████████████████████████████████████████████████████| 64/64 [00:05<00:00, 11.43it/s]
Starting Prior
prior\diffusion_pytorch_model.safetensors not found
Pipelines loaded with `torch_dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `torch_dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `torch_dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Loading weights [6ce0161689] from C:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Disabling attention optimization
*** Error completing request
*** Arguments: ('task(i83ngnlvhf5umb9)', ' cat, realistic, high quality, 4k', '', [], 64, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 4, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, 128, 0.5, 0.5) {}
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "C:\stable-diffusion-webui\modules\processing.py", line 607, in process_images
        sd_models.reload_model_weights()
      File "C:\stable-diffusion-webui\modules\sd_models.py", line 553, in reload_model_weights
        load_model(checkpoint_info, already_loaded_state_dict=state_dict)
      File "C:\stable-diffusion-webui\modules\sd_models.py", line 511, in load_model
        sd_model.cond_stage_model_empty_prompt = sd_model.cond_stage_model([""])
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 229, in forward
        z = self.process_tokens(tokens, multipliers)
      File "C:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 254, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "C:\stable-diffusion-webui\modules\sd_hijack_clip.py", line 302, in encode_with_transformers
        outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
        return self.text_model(
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\transformers\models\clip\modeling_clip.py", line 721, in forward
        encoder_outputs = self.encoder(
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\transformers\models\clip\modeling_clip.py", line 650, in forward
        layer_outputs = encoder_layer(
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\transformers\models\clip\modeling_clip.py", line 379, in forward
        hidden_states, attn_weights = self.self_attn(
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\transformers\models\clip\modeling_clip.py", line 268, in forward
        query_states = self.q_proj(hidden_states) * self.scale
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\extensions-builtin\LoraBKP\lora.py", line 400, in lora_Linear_forward
        return torch.nn.Linear_forward_before_lora(self, input)
      File "C:\stable-diffusion-webui\venvxformers\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility
```

**Comment by AugmentedRealityCat** [comment]
I do have a `diffusion_pytorch_model.bin` over there, so it's the same filename, but as a `.bin` file instead of `.safetensors`. 
Is that OK ?

I will remove the folder and report back.

Thanks for your help !

**Comment by MMqd** [comment]
On my installation its prior\diffusion_pytorch_model.safetensors. What mode where you running: text2img, img2img, image mixing (when an image is included in the script section), inpaint?

**Comment by AugmentedRealityCat** [comment]
Rereading the log, I found this line that might be a clue:
`image_encoder\model.safetensors not found`

**Comment by MMqd** [comment]
To be honest I'm not sure why that is happening. I have only tested on Linux, but I will try it on Windows.

**Comment by AugmentedRealityCat** [comment]
Good news: with the latest update, it installed a lot of what I suppose were missing dependencies and now it works ! I still get many error messages, but also an image :)
