### ISSUE TITLE
Support macOS ARM

### ISSUE THREAD

**Issue by x-0D** [MMqd/kandinsky-for-automatic1111#12]
```
LatentDepth2ImageDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Applying attention optimization: V1... done.
Model loaded in 30.9s (load weights from disk: 4.9s, create model: 2.7s, apply weights to model: 18.9s, load textual inversion embeddings: 2.2s, calculate empty prompt: 2.0s).
Unloaded weights 0.0s.
*** Error completing request
*** Arguments: ('task(wjnjn6pkgdp7nep)', 'cinematic photo close-up portrait of a young Austrian woman, with striking facial details, her eyes being the focal point, clear, expressive, and in sharp focus, her skin glowing under soft lighting, her features accentuated by subtle makeup, her expression captivating and engaging . 35mm photograph, film, bokeh, professional, 4k, highly detailed', 'cartoon, anime, sketch, painting, low quality, blurry, grayscale, out of focus, distorted, deformed, mutated, cross-eyed, closed eyes, bad anatomy, ugly, disfigured, sloppy, duplicate, drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x2900044f0>, 4, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, 128, 4, 0.5, 0.5) {}
    Traceback (most recent call last):
      File "/Users/appleroot/Documents/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/Users/appleroot/Documents/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/Users/appleroot/Documents/stable-diffusion-webui/modules/txt2img.py", line 59, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "/Users/appleroot/Documents/stable-diffusion-webui/modules/scripts.py", line 501, in run
        processed = script.run(p, *script_args)
      File "/Users/appleroot/Documents/stable-diffusion-webui/extensions/kandinsky-for-automatic1111/scripts/kandinsky.py", line 214, in run
        if version.parse(torch.version.cuda) < version.parse("10.2"):
      File "/opt/homebrew/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
        return Version(version)
      File "/opt/homebrew/lib/python3.10/site-packages/packaging/version.py", line 196, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
```

**Comment by MMqd** [comment]
I don't have a mac to test this on, but the error should be fixed now.
