### ISSUE TITLE
NameError: name 'CLIPVisionModelWithProjection' is not defined

### ISSUE THREAD

**Issue by nikolaiusa** [MMqd/kandinsky-for-automatic1111#14]
model 2.2 i did not upload - Should the download start automatically?
After setup and restart SD: 

Starting Prior
Error completing request
Arguments: ('task(640qqqw29a93lvf)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 4, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, 64, 4, '2.2', 0.5, 0.5, True) {}
Traceback (most recent call last):
  File "I:\stable-diffusion-webui-1.3.2\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "I:\stable-diffusion-webui-1.3.2\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "I:\stable-diffusion-webui-1.3.2\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "I:\stable-diffusion-webui-1.3.2\modules\scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "I:\stable-diffusion-webui-1.3.2\extensions\kandinsky-for-automatic1111\scripts\kandinsky_script.py", line 107, in run
    return shared.kandinsky_model.process_images(p)
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\abstract_model.py", line 260, in process_images
    self.load_encoder()
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\kandinsky.py", line 80, in load_encoder
    self.image_encoder = CLIPVisionModelWithProjection.from_pretrained(
NameError: name 'CLIPVisionModelWithProjection' is not defined

**Comment by nikolaiusa** [comment]
i changed the version and it worked


Successfully uninstalled diffusers-0.17.1
Successfully installed diffusers-0.20.0

**Comment by nikolaiusa** [comment]
but in 2.1 error)

Error completing request
Arguments: ('task(lpu1km615n9j5e1)', 'cat', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 4, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, 64, 4, '2.1', 0.5, 0.5, False) {}
Traceback (most recent call last):
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\abstract_model.py", line 398, in process_images
    self.main_model_to_cpu()
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\kandinsky.py", line 166, in main_model_to_cpu
    self.pipe.to("cpu")
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 727, in to
    module.to(torch_device, torch_dtype)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\stable-diffusion-webui-1.3.2\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "I:\stable-diffusion-webui-1.3.2\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "I:\stable-diffusion-webui-1.3.2\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "I:\stable-diffusion-webui-1.3.2\modules\scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "I:\stable-diffusion-webui-1.3.2\extensions\kandinsky-for-automatic1111\scripts\kandinsky_script.py", line 107, in run
    return shared.kandinsky_model.process_images(p)
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\abstract_model.py", line 438, in process_images
    self.cleanup_on_error()
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\kandinsky.py", line 220, in cleanup_on_error
    self.main_model_to_cpu()
  File "I:\stable-diffusion-webui-1.3.2\extensions/kandinsky-for-automatic1111/scripts\kandinsky.py", line 166, in main_model_to_cpu
    self.pipe.to("cpu")
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 727, in to
    module.to(torch_device, torch_dtype)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "I:\stable-diffusion-webui-1.3.2\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by nikolaiusa** [comment]
I:\stable-diffusion-webui-1.3.2\extensions\kandinsky-for-automatic1111\scripts\kandinsky.py
i changed line 21 and 2.1 worked

21    move_to_cuda=True

**Comment by nikolaiusa** [comment]
and another question - what needs to be changed to use Kandinsky offline?


requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/kandinsky-community/kandinsky-2-1-prior (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000211B78E0CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"), '(Request ID: 17cfaf22-a980-47c0-983c-75d343d72d65)')
