### ISSUE TITLE
Diffusers not installing during extension installation

### ISSUE THREAD

**Issue by MMqd** [MMqd/kandinsky-for-automatic1111#2]
Diffusers not installing from git causing script execution to fail. I was able to replicate this behavior on runpod. Currently a quick fix is to edit `requirements.txt` and replace `diffusers==???` where `???` is a version with `diffusers`, and reinstall the extension.

```webui-docker-auto-1  | Restarting UI...
webui-docker-auto-1  | Closing server running on port: 7860
webui-docker-auto-1  | Error loading script: kandinsky.py
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
webui-docker-auto-1  |     script_module = script_loading.load_module(scriptfile.path)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
webui-docker-auto-1  |     module_spec.loader.exec_module(module)
webui-docker-auto-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/kandinsky-for-automatic1111/scripts/kandinsky.py", line 2, in <module>
webui-docker-auto-1  |     from diffusers import DiffusionPipeline, KandinskyPipeline, KandinskyImg2ImgPipeline, KandinskyPriorPipeline, KandinskyInpaintPipeline, DPMSolverMultistepScheduler
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/diffusers/__init__.py", line 4, in <module>
webui-docker-auto-1  |     from .utils import (
webui-docker-auto-1  | ImportError: cannot import name 'is_torchsde_available' from 'diffusers.utils' (/usr/local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
webui-docker-auto-1  |
webui-docker-auto-1  | 2023-06-11 22:29:24,017 - ControlNet - INFO - ControlNet v1.1.220
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 28, in <module>
webui-docker-auto-1  |     from dreambooth.diff_to_sd import compile_checkpoint
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 15, in <module>
webui-docker-auto-1  |     from diffusers import UNet2DConditionModel
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/diffusers/__init__.py", line 4, in <module>
webui-docker-auto-1  |     from .utils import (
webui-docker-auto-1  | ImportError: cannot import name 'is_torchsde_available' from 'diffusers.utils' (/usr/local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
webui-docker-auto-1  | Exception importing api
webui-docker-auto-1  | Error loading script: main.py
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
webui-docker-auto-1  |     script_module = script_loading.load_module(scriptfile.path)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
webui-docker-auto-1  |     module_spec.loader.exec_module(module)
webui-docker-auto-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
webui-docker-auto-1  |     from dreambooth.diff_to_sd import compile_checkpoint
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 15, in <module>
webui-docker-auto-1  |     from diffusers import UNet2DConditionModel
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/diffusers/__init__.py", line 4, in <module>
webui-docker-auto-1  |     from .utils import (
webui-docker-auto-1  | ImportError: cannot import name 'is_torchsde_available' from 'diffusers.utils' (/usr/local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
webui-docker-auto-1  |
webui-docker-auto-1  | Running on local URL:  http://0.0.0.0:7860
webui-docker-auto-1  |
webui-docker-auto-1  | To create a public link, set `share=True` in `launch()`.
webui-docker-auto-1  | Startup time: 1.0s (load scripts: 0.3s, create ui: 0.5s).
webui-docker-auto-1  | Restarting UI...
webui-docker-auto-1  | Closing server running on port: 7860
webui-docker-auto-1  | Error loading script: kandinsky.py
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
webui-docker-auto-1  |     script_module = script_loading.load_module(scriptfile.path)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
webui-docker-auto-1  |     module_spec.loader.exec_module(module)
webui-docker-auto-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/kandinsky-for-automatic1111/scripts/kandinsky.py", line 2, in <module>
webui-docker-auto-1  |     from diffusers import DiffusionPipeline, KandinskyPipeline, KandinskyImg2ImgPipeline, KandinskyPriorPipeline, KandinskyInpaintPipeline, DPMSolverMultistepScheduler
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/diffusers/__init__.py", line 4, in <module>
webui-docker-auto-1  |     from .utils import (
webui-docker-auto-1  | ImportError: cannot import name 'is_torchsde_available' from 'diffusers.utils' (/usr/local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
webui-docker-auto-1  |
webui-docker-auto-1  | 2023-06-11 22:33:55,601 - ControlNet - INFO - ControlNet v1.1.220
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 28, in <module>
webui-docker-auto-1  |     from dreambooth.diff_to_sd import compile_checkpoint
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 15, in <module>
webui-docker-auto-1  |     from diffusers import UNet2DConditionModel
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/diffusers/__init__.py", line 4, in <module>
webui-docker-auto-1  |     from .utils import (
webui-docker-auto-1  | ImportError: cannot import name 'is_torchsde_available' from 'diffusers.utils' (/usr/local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
webui-docker-auto-1  | Exception importing api
webui-docker-auto-1  | Error loading script: main.py
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
webui-docker-auto-1  |     script_module = script_loading.load_module(scriptfile.path)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
webui-docker-auto-1  |     module_spec.loader.exec_module(module)
webui-docker-auto-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
webui-docker-auto-1  |     from dreambooth.diff_to_sd import compile_checkpoint
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 15, in <module>
webui-docker-auto-1  |     from diffusers import UNet2DConditionModel
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/diffusers/__init__.py", line 4, in <module>
webui-docker-auto-1  |     from .utils import (
webui-docker-auto-1  | ImportError: cannot import name 'is_torchsde_available' from 'diffusers.utils' (/usr/local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
webui-docker-auto-1  |
webui-docker-auto-1  | Running on local URL:  http://0.0.0.0:7860
webui-docker-auto-1  |
webui-docker-auto-1  | To create a public link, set `share=True` in `launch()`.
webui-docker-auto-1  | Startup time: 1.1s (load scripts: 0.3s, create ui: 0.5s).```

**Comment by AugmentedRealityCat** [comment]
Should there be a specific requirements.txt file in the Kandinsky extension's folder itself ? Or somewhere else ? I have one for the main app (Automatic1111-WebUI) and for some extensions, but there doesn't seem to be any in the `stable-diffusion-webui\extensions\kandinsky-for-automatic1111` folder, nor in its subfolders.

**Comment by MMqd** [comment]
The `requirements.txt` file should be in the main app folder, so `stable-diffusion-webui/requirements.txt`.

**Comment by MMqd** [comment]
Same issue as #4, added errors during installation and troubleshooting instructions to README, telling the user to restart Automatic1111 completely.
