### ISSUE TITLE
Error With Diffusers

### ISSUE THREAD

**Issue by frankjoshua** [MMqd/kandinsky-for-automatic1111#4]
Error loading script: kandinsky.py
Traceback (most recent call last):
  File "/var/cache/models/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/var/cache/models/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/cache/models/stable-diffusion-webui/extensions/kandinsky-for-automatic1111/scripts/kandinsky.py", line 2, in <module>
    from diffusers import DiffusionPipeline, KandinskyPipeline, KandinskyImg2ImgPipeline, KandinskyPriorPipeline, KandinskyInpaintPipeline, DPMSolverMultistepScheduler
ImportError: cannot import name 'KandinskyPipeline' from 'diffusers' (/home/josh/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/__init__.py)

**Comment by wbclark** [comment]
dreambooth sets a requirement for diffusers~=0.16.1

that or another addon is likely causing the conflict for you

**Comment by MMqd** [comment]
As a quick fix try changing the line `diffusers==???` to `diffusers>=0.17.1` in `stable-diffusion-webui/requirements.txt`. If there is no such line, then add `diffusers>=0.17.1`. I'm already working on this in the installer.

**Comment by Renaldas111** [comment]
The same error even after adding diffusers>=0.17.1 to requirements.txt

**Comment by MMqd** [comment]
Try restarting completely not just by clitking "Apply & restart", so it uses the latest version.

**Comment by MMqd** [comment]
Known issue, added errors during installation and troubleshooting instructions to README, telling the user to restart Automatic1111 completely.
